### ISSUE TITLE
Getting the last message as part of the channel object

### ISSUE THREAD

**Issue by lukepighetti** [GetStream/stream-chat-dart#19]
Hey guys, this is more of a general question. We are getting the list of channels when querying a channel along with the last message date, but there's no data about what the actual last message is. Does Stream just not provide this data on any of their APIs or is the Dart API incomplete in this area?

**Comment by lukepighetti** [comment]
This appears to be available in the JavaScript SDK but not the Dart SDK.

```js
  lastMessage(): Message;
```

**Comment by imtoori** [comment]
I think we don't provide the last message on any API, the one you pointed out is just a getter that extracts the last message from the list of messages
I think that's useful and simple, I'll add it in the next release

**Comment by lukepighetti** [comment]
Hi! Didn't realize you could get the list of messages. I found the Channel.state getter to be undocumented. That solves my issue.
