### ISSUE TITLE
Getting the unread count on a channel

### ISSUE THREAD

**Issue by lukepighetti** [GetStream/stream-chat-dart#20]
Hey guys, the JavaScript SDK appears to have a few unread count methods on the Channel object, 

```js
  countUnreadMentions(): number;
  countUnread(lastRead?: Date): number;
```

How do we access these in the Dart SDK? Specifically `countUnread()`. There appear to be no getters or methods on class `Channel`

**Comment by imtoori** [comment]
Hey Luke,
you can find the `unreadCount` getter in `channel.state.unreadCount`

**Comment by lukepighetti** [comment]
Thanks!
